### PR TITLE
Fix Pipfile & set up Travis

### PR DESCRIPTION
**Pull request by neanias**

### CODE REVIEW

**Review by qaisjp — APPROVED** [review]

**Review by qaisjp — CHANGES_REQUESTED** [review]
There appears to be a runtime error: 

```
web_1    | [2018-10-31 12:05:02 +0000] [11] [ERROR] Exception in worker process
web_1    | Traceback (most recent call last):
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1    |     worker.init_process()
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
web_1    |     self.load_wsgi()
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
web_1    |     self.wsgi = self.app.wsgi()
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1    |     self.callable = self.load()
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
web_1    |     return self.load_wsgiapp()
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
web_1    |     return util.import_app(self.app_uri)
web_1    |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
web_1    |     __import__(module)
web_1    |   File "/code/map/__init__.py", line 12, in <module>
web_1    |     from . import views
web_1    |   File "/code/map/views.py", line 9, in <module>
web_1    |     from map import app, flask_redis, ldap
web_1    | ImportError: cannot import name 'app' from 'map' (/code/map/__init__.py)
```

**Review by qaisjp — CHANGES_REQUESTED** [review]
A 404 is now being reported for all pages.

```
 * Serving Flask app "map:app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:9000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 155-229-607
192.41.131.250 - - [31/Oct/2018 15:52:19] "GET / HTTP/1.0" 404 -
192.41.131.250 - - [31/Oct/2018 15:52:49] "GET /about HTTP/1.0" 404 -
192.41.131.250 - - [31/Oct/2018 15:52:52] "GET /site/6.06 HTTP/1.0" 404 -
192.41.131.250 - - [31/Oct/2018 15:52:58] "GET / HTTP/1.0" 404 -
```

image

**Comment by neanias** [comment]
Oh, joy

**Review by qaisjp — CHANGES_REQUESTED** [review]
This new class scares me but I'll survive.

Here's another error: 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
TypeError: site() missing 1 required positional argument: 'self'
```

**Comment by neanias** [comment]
@qaisjp, what action caused this error?

**Comment by qaisjp** [comment]
> @qaisjp, what action caused this error?

After logging in, visiting /site/6.06.

**Review by qaisjp — CHANGES_REQUESTED** [review]
This is a new error, on visiting `/` whilst not logged in:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 330, in __call__
    rv = self._load_unlocked()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 242, in locate_app
    '\n\n{tb}'.format(name=module_name, tb=traceback.format_exc())
flask.cli.NoAppException: While importing "map", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/code/map/__init__.py", line 38, in <module>
    app = create_app()
  File "/code/map/__init__.py", line 20, in create_app
    from .blueprints import api, auth, views
  File "/code/map/blueprints/api.py", line 13, in <module>
    from .ldaptools import LDAPTools
ModuleNotFoundError: No module named 'map.blueprints.ldaptools'
```

**Comment by qaisjp** [comment]
That fixed the error.

New error (`GET /` not logged in)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/code/map/__init__.py", line 38, in <module>
    app = create_app()
  File "/code/map/__init__.py", line 20, in create_app
    from .blueprints import api, auth, views
  File "/code/map/blueprints/api.py", line 16, in <module>
    bp.config.from_object('config')
AttributeError: 'Blueprint' object has no attribute 'config'
```

**Comment by qaisjp** [comment]
It saddens me to close this but it likely will never be merged. Too many changes / too buggy.

It is worth slow incorporating changes from this PR still

**Pull request closed without merging**
